// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Swatch: typeof import('./src/components/Swatch.vue')['default']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VSheet: typeof import('vuetify/lib')['VSheet']
  }
}

export { }
