// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    VBtn: typeof import('vuetify/lib')['VBtn']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VSheet: typeof import('vuetify/lib')['VSheet']
    VSwatches: typeof import('./src/components/VSwatches.vue')['default']
  }

}
