import { writeFileSync } from 'node:fs';
import { fileURLToPath, URL } from 'node:url';

import vue from '@vitejs/plugin-vue';
import { defineConfig } from 'vite';
/// <reference types="vitest" />

import { visualizer } from 'rollup-plugin-visualizer';
import banner from 'vite-plugin-banner';
import { checker } from 'vite-plugin-checker';
import dts from 'vite-plugin-dts';
import vuetify, { transformAssetUrls } from 'vite-plugin-vuetify';

import pkg from './package.json';

// https://vitejs.dev/config/
export default defineConfig(({ command, mode }) => {
  const config = {
    resolve: {
      // https://vitejs.dev/config/shared-options.html#resolve-alias
      alias: {
        '@': fileURLToPath(new URL('./src', import.meta.url)),
        '~': fileURLToPath(new URL('./node_modules', import.meta.url)),
        'vuetify-swatches': fileURLToPath(new URL('./src', import.meta.url)),
      },
      // External
      dedupe: ['vue', 'vuetify'],
    },
    // https://vitejs.dev/config/shared-options.html#base
    base: './',
    plugins: [
      // Vue3
      vue({
        template: {
          // https://github.com/vuetifyjs/vuetify-loader/tree/next/packages/vite-plugin#image-loading
          transformAssetUrls,
        },
      }),
      // Vuetify Loader
      // https://github.com/vuetifyjs/vuetify-loader
      mode === 'docs'
        ? vuetify({
            autoImport: true,
            styles: 'sass',
          })
        : undefined,
      // vite-plugin-checker
      // https://github.com/fi3ework/vite-plugin-checker
      checker({
        typescript: true,
        // vueTsc: true,
      }),
      // vite-plugin-banner
      // https://github.com/chengpeiquan/vite-plugin-banner
      banner(`/**
 * ${pkg.name}
 *
 * @description ${pkg.description}
 * @author ${pkg.author.name} <${pkg.author.email}>
 * @copyright 2022-${new Date().getFullYear()} By Masashi Yoshikawa All rights reserved.
 * @license ${pkg.license}
 * @version ${pkg.version}
 * @see {@link ${pkg.homepage}}
 */
`),
      // vite-plugin-dts
      // https://github.com/qmhc/vite-plugin-dts
      mode === 'docs'
        ? undefined
        : dts({ tsconfigPath: './tsconfig.app.json' }),
    ],
    optimizeDeps: {
      exclude: ['vue'],
    },
    // Build Options
    // https://vitejs.dev/config/#build-options
    build: {
      commonjsOptions: {
        exclude:
          mode === 'docs'
            ? undefined
            : [
                'vuetify/lib',
                'vuetify/lib/components/VBtn',
                'vuetify/lib/components/VIcon',
                'vuetify/lib/components/VSheet',
                'vuetify/util/colors',
              ],
      },
      outDir: mode === 'docs' ? 'docs' : undefined,
      lib:
        mode === 'docs'
          ? undefined
          : {
              entry: fileURLToPath(new URL('./src/index.ts', import.meta.url)),
              name: 'VSwatches',
              formats: ['umd', 'es', 'cjs', 'iife'] as const,
              fileName: (format: string) => `index.${format}.js`,
            },
      rollupOptions: {
        plugins: [
          mode === 'analyze'
            ? // rollup-plugin-visualizer
              // https://github.com/btd/rollup-plugin-visualizer
              visualizer({
                open: true,
                filename: 'dist/stats.html',
                gzipSize: true,
                brotliSize: true,
              })
            : undefined,
        ],
        external: mode === 'docs' ? undefined : ['vue', /^vuetify/],
        output: {
          esModule: true,
          generatedCode: {
            reservedNamesAsProps: false,
          },
          interop: 'compat' as const,
          systemNullSetters: false,
          exports: 'named' as const,
          globals: {
            vue: 'Vue',
            'vuetify/components': 'Vuetify/components',
            'vuetify/util/colors': 'colors',
          },
          manualChunks:
            mode === 'docs'
              ? {
                  vue: ['vue'],
                  vuetify: [
                    'vuetify/components',
                    'vuetify/directives',
                    'vuetify/util/colors',
                  ],
                  codemirror: ['vue-codemirror6'],
                  'codemirror-lang': ['@codemirror/lang-vue'],
                }
              : undefined,
        },
      },
      target: 'esnext',
      // minify: mode === 'docs',
    },
    esbuild: {
      drop: command === 'serve' ? [] : ['console' as const],
    },
  };
  // Write meta data.
  writeFileSync(
    fileURLToPath(new URL('./src/Meta.ts', import.meta.url)),
    `import type MetaInterface from './interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '${pkg.version}',
  date: '${new Date().toISOString()}',
};
export default meta;
`
  );
  // Export vite config
  return config;
});
